#!/bin/sh

daemon=tinydb

die() {
	echo $@
	exit 1
}

showUsage() {
	die "$0 {start|stop|restart|status} [prefix]"
}

start() {
	tmpdb=/tmp/nor.db
	ramfsdb=/etc/db/dbinput.db

	echo -n "Setting up $daemon... "
	[ -x $binary ] || die "$binary is not a valid application."
	export LD_LIBRARY_PATH=$prefix/lib
	# do it
	#$binary init > /dev/null 2> /dev/null
	/usr/sbin/import -a /etc/db/actinput.db > /tmp/tinydb.log 2> /tmp/tinydb.err || {
		echo -n "damaged, reparing... "
		erasenor 1 >> /tmp/tinydb.log 2>> /tmp/tinydb.err
		echo -n "ok, data will be reset... "
		reboot
		die "rebooting..."
	}
	# ignore return of init command
	[ -f $ramfsdb ] && eval $($binary meta $ramfsdb) || die "ng."
	norETag=$($binary get Meta ETag_ms) || die "ng."
	if [ "$metaETag" != "$norETag" ]; then
		echo -n "migrating... "
		$binary export $tmpdb &&
			$binary migrate $ramfsdb > /dev/null &&
			$binary import $tmpdb || die "ng."
		rm -f $tmpdb
	fi
	
	# test if just factory reset
	[ "$(tdb get Host CameraName_ms)" ] || { 
		echo -n "set default..."
		model=$([ "$(pibinfo Wireless)" -eq 1 ] && tdb get System ModelW_ss || tdb get System Model_ss)
		tdb set Host CameraName_ms=$model
		tdb set OSD Text_ss=$model
		tdb set FTPClient1 Prefix_ss=$model
		tdb set FTPClient2 Prefix_ss=$model
		echo "ok."

		eval $(image_controller status)
		if [ "$DISPLAY_SYSTEM" = "PAL" ]; then
			echo -n "modify default resolution for PAL system... "
			tdb set Profile1 FPS_byte=25
			tdb set Profile2 FPS_byte=8
			tdb set Profile3 FPS_byte=8
			echo "ok."
		fi

		echo "set the date to default:"
		date 010112002010
		hwclock -w -u

	}
}

status() {
	echo -n "$daemon"
	echo "($(tdb get Meta ETag_ms)) is using." || echo " is not available."
}

stop() {
	echo "Stop $daemon is no need."
}

action=$1
prefix=$2
end=$3

[ "$end" = "" ] && [ "$action" != "" ] || showUsage
[ "$prefix" = "" ] || [ -d "$prefix" ] || die "$prefix is not a valid directory."

binary=$prefix/bin/tdb

case $action in
	start)
		start
	;;
	stop)
		stop
	;;
	restart)
		stop
		start
	;;
	status)
		status
	;;
	*)
		showUsage
	;;
esac

exit 0
